# Generated by Django 6.0 on 2026-08-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_manage_app', '0002_department_employee_task_extensionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='extensionrequest',
            name='task',
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ExtensionRequest',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
