from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("work_manage_app", "0003_remove_employee_department_remove_task_employee_and_more")]
    operations = [
        migrations.CreateModel(name="Department", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100, unique=True)), ("description", models.TextField(blank=True))]),
        migrations.CreateModel(name="EmployeeDepartment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("designation", models.CharField(blank=True, max_length=100)), ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employees", to="work_manage_app.department")), ("employee", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="department_assignment", to="work_manage_app.register"))]),
        migrations.CreateModel(name="Task", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=200)), ("description", models.TextField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("deadline", models.DateField()), ("status", models.CharField(choices=[("Pending", "Pending"), ("In Progress", "In Progress"), ("Completed", "Completed"), ("Overdue", "Overdue")], default="Pending", max_length=20)), ("priority", models.CharField(choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")], default="Medium", max_length=10)), ("progress", models.PositiveIntegerField(default=0)), ("assigned_to", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="work_manage_app.register")), ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="work_manage_app.department"))]),
        migrations.CreateModel(name="ProgressUpdate", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("progress", models.PositiveIntegerField()), ("note", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_updates", to="work_manage_app.register")), ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="work_manage_app.task"))]),
        migrations.CreateModel(name="ExtensionRequest", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("requested_deadline", models.DateField()), ("reason", models.TextField()), ("status", models.CharField(choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")], default="Pending", max_length=20)), ("admin_note", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extension_requests", to="work_manage_app.register")), ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="extension_requests", to="work_manage_app.task"))]),
        migrations.CreateModel(name="Notification", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=150)), ("message", models.TextField()), ("is_read", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="work_manage_app.register"))]),
        migrations.CreateModel(name="Message", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("subject", models.CharField(max_length=200)), ("body", models.TextField()), ("is_read", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="received_messages", to="work_manage_app.register")), ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_messages", to="work_manage_app.register"))]),
    ]
