# Generated by Django 6.0 on 2026-09-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_manage_app', '0012_alter_extensionrequest_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='progress_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='work_manage_app.progressupdate'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending approval'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=10),
        ),
    ]
