from django.urls import path
from . import views
from .admin_actions import employee_delete

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("register/departments/", views.registration_departments, name="registration_departments"),
    path("login/", views.login_view, name="login"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("reset-password/<uidb64>/<token>/", views.reset_password, name="reset_password"),
    path("logout/", views.logout, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("adminlogin/", views.adminlogin, name="adminlogin"),
    path("admin/dashboard/", views.admin_dash, name="admin_dash"),
    path("admin/logout/", views.adminlogout, name="adminlogout"),
    path("admin/employees/", views.employee_management, name="employee_management"),
    path("admin/employees/<int:employee_id>/edit/", views.employee_edit, name="employee_edit"),
    path("admin/employees/<int:employee_id>/delete/", employee_delete, name="employee_delete"),
    path("admin/departments/", views.department_management, name="department_management"),
    path("admin/departments/<int:department_id>/delete/", views.department_delete, name="department_delete"),
    path("admin/tasks/", views.task_management, name="task_management"),
    path("admin/tasks/assign/", views.assign_task, name="assign_task"),
    path("admin/extensions/", views.extension_requests, name="extension_requests"),
    path("admin/extensions/<int:request_id>/<str:action>/", views.extension_action, name="extension_action"),
    path("admin/reports/", views.reports, name="reports"),
    path("admin/notifications/", views.admin_notifications, name="admin_notifications"),
    path("admin/messages/", views.admin_messages, name="admin_messages"),
    path("admin/profile/", views.admin_profile, name="admin_profile"),
    path("tasks/", views.employee_tasks, name="employee_tasks"),
    path("tasks/<int:task_id>/", views.task_detail, name="task_detail"),
    path("progress-updates/", views.progress_updates, name="progress_updates"),
    path("tasks/<int:task_id>/progress/", views.progress_update, name="progress_update"),
    path("extension-requests/", views.extension_requests_employee, name="extension_requests_employee"),
    path("tasks/<int:task_id>/extension/", views.request_extension, name="request_extension"),
    path("notifications/", views.notifications, name="notifications"),
    path("messages/", views.messages_view, name="messages"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings_view, name="settings"),
]
